/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collector;
import java.util.stream.Collectors;

public class App {
   

    public static void main(String[] args) {
    List<Integer>l=Arrays.asList(1,2,3,4,5,6,7,8,9);
    l.stream().map(e-> e*2).collect(Collectors.toList());
}
    

   
}